[package]
name = "light-controller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lights = {path = "lights"}
log = "0.4.17"
env_logger = "0.10.0"

[lib]
crate-type = ["cdylib", "rlib"]